### ISSUE TITLE
[BUG]: method testBuild now requires nonnull parameter

### ISSUE THREAD

**Issue by UsainSrht** [YouHaveTrouble/YardWatch#3]
### Plugin name

WorldGuard

### What happened?

```
Caused by: java.lang.NullPointerException: The build flag is handled in a special fashion and requires a non-null subject parameter
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.FlagValueCalculator.queryAllValues(FlagValueCalculator.java:392) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.FlagValueCalculator.queryValue(FlagValueCalculator.java:227) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.FlagValueCalculator.queryState(FlagValueCalculator.java:174) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.RegionResultSet.queryState(RegionResultSet.java:103) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.regions.RegionQuery.queryState(RegionQuery.java:320) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.regions.RegionQuery.testState(RegionQuery.java:275) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at worldguard-bukkit-7.0.11-beta1-dist.jar/com.sk89q.worldguard.protection.regions.RegionQuery.testBuild(RegionQuery.java:161) ~[worldguard-bukkit-7.0.11-beta1-dist.jar:?]
        at YardWatch-1.2.0.jar/me.youhavetrouble.yardwatch.hooks.WorldGuardProtection.isProtected(WorldGuardProtection.java:37) ~[YardWatch-1.2.0.jar:?]
```

### Sanity checks

- [X] I made sure there isn't an open issue about this already

**Comment by YouHaveTrouble** [comment]
fixed in 1.3.0
